version: '3.8'

services:
  postgres_address:
    image: postgres:15
    container_name: address_db_container
    environment:
      POSTGRES_DB: address_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root1234
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5433:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: your_email@example.com
      PGADMIN_DEFAULT_PASSWORD: root1234
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres_address

volumes:
  pgadmin_data:
